### ISSUE TITLE
Expose <svg> tags

### ISSUE THREAD

**Issue by 008v** [pocketsvg/PocketSVG#144] opened 2019-01-17 04:53 UTC
I want to get some attributes of the SVG tag, such as viewbox.

**Comment by vaibhav-jhaveri-ds** [comment] 2019-01-18 13:53
Same here

**Comment by arielelkin** [comment] 2019-01-18 21:58
There are dozens of SVG tags (https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute), so please specify which ones you'd like to see exposed.

**Comment by vaibhav-jhaveri-ds** [comment] 2019-01-19 04:55
@arielelkin, I think @008v already has mentioned one such property `viewBox`. Others may include `height`, `width`, `x`, `y`, etc

**Comment by 008v** [comment] 2019-01-23 03:19
@arielelkin 
width, height and viewBox.

**Comment by zzyspace** [comment] 2019-06-06 02:32
> @arielelkin
> `width`, `height` and `viewBox`.
> 
> I used Metal to render SVG. The first thing is transform the coordinate, convert svg coordinate to screen coordinate, and then to NDC. I need to get the `viewBox`, `width`, and `height` of `<svg>` tag to generate the matrix.

Have you found a solution?

**Comment by arielelkin** [comment] 2019-06-06 14:01
I have taken a second look at this and realise it's not clear what the issue is.

The SVG tags are readily available to you as you're already providing the SVG file. Getting the original SVG attributes themselves is outside the scope of PocketSVG, as that can (and should) be done by a generic XML parser. 

Another reason it doesn't make sense for PocketSVG types to expose the original SVG's `width` `height` and `viewBox` is because these values make little sense in a Core Graphics context, and could lead to confusion with `SVGLayer`'s native `width` and `height` properties or `SVGImageView`'s `bounds` property.

@zzyspace @008v @vaibhav-jhaveri-ds if you had something different in mind, could you please elaborate on what you are trying to achieve?

**Comment by arielelkin** [comment] 2019-06-19 16:46
Closing due to issue not seemingly applicable, but feel free to reopen with further elaboration if need be.

**Closed by arielelkin** 2019-06-19 16:46 UTC
Labels: feature request

**Comment by MrDuncanM** [comment] 2019-06-20 15:29
I ended up using svgkit.
