### ISSUE TITLE
Carthage installation error 

### ISSUE THREAD

**Issue by linhleduy** [pocketsvg/PocketSVG#190] opened 2021-03-04 04:48 UTC
### Steps to reproduce the issue

  1. add `github "pocketsvg/PocketSVG" ~> 2.6`
  2. carthage update
  3. Error message appears : "Dependency "PocketSVG" has no shared framework schemes"

### Specifications

  - PocketSVG Version:  2.6.0
  - Xcode Version: 12.0.1
  - iOS/macOS Version:

**Comment by arielelkin** [comment] 2021-03-22 10:16
@linhleduy just a quick update from me. I'm able to reproduce your issue but I can't figure out a fix. 

I opened an issue over at Carthage: https://github.com/Carthage/Carthage/issues/3146

Will keep you posted!

**Comment by arielelkin** [comment] 2021-12-16 10:47
looks like this has been fixed in Xcode 13. Feel free to reopen this ticket if there are still issues.

**Closed by arielelkin** 2021-12-16 10:47 UTC
