### ISSUE TITLE
OS X crash.

### ISSUE THREAD

**Issue by VladislavShchegolev** [pocketsvg/PocketSVG#136] opened 2018-10-26 08:05 UTC
### Steps to reproduce the issue

  1. Just create an instance of SVGImageView

**let svgImageView = SVGImageView()**

From the crash report:
`Crashing on exception: Views must return a valid layer from -makeBackingLayer.`

### Specifications

  - PocketSVG Version: 2.4.1 - newest
  - Xcode Version: 9.2
  - macOS Version: 10.14

**Comment by arielelkin** [comment] 2018-11-25 12:37
Hi @VladislavShchegolev 

I'm unable to reproduce this. I have the same Xcode and PocketSVG versions, tried running the `Demo-macOS` target in `PocketSVG/Demos/Demos.xcworkspace` which also creates an instance of `SVGImageView`.

Are you getting the same crash when running `Demo-macOS`?

**Comment by arielelkin** [comment] 2018-12-03 23:38
closing due to inactivity. feel free to reopen.

**Comment by VladislavShchegolev** [comment] 2018-12-04 02:53
![screenshot 2018-12-04 at 09 51 40](https://user-images.githubusercontent.com/27974329/49415782-4fcaec80-f7aa-11e8-8c3a-4519be814f42.png)
It is not crashing now (2.4.2) but the error is the same 

> Views must return a valid layer from -makeBackingLayer.

**Comment by arielelkin** [comment] 2018-12-04 08:43
Again, I'm unable to reproduce this. Can you reproduce it from a clean clone of the project?

**Comment by gabor-nemeth** [comment] 2019-01-24 19:55
I also experience this issue, even with a clean clone. It gets fixed, if you change the order of [these lines](https://github.com/pocketsvg/PocketSVG/blob/master/SVGImageView.m#L46-L47). `makeBackingLayer` is called by `self.wantsLayer = YES` and `_svgLayer` is `nil` at this time.
The same is true for the `initWithCoder` method.

I use XCode 10.1 on OS X 10.14.

**Comment by arielelkin** [comment] 2019-01-30 20:44
@gabor-nemeth @VladislavShchegolev 

I am able to reproduce it now. 

I'm submitting a PR with the fix, you're welcome to review and comment:
https://github.com/pocketsvg/PocketSVG/pull/149

**Comment by arielelkin** [comment] 2019-03-12 08:43
closed via https://github.com/pocketsvg/PocketSVG/pull/149

**Closed by arielelkin** 2019-03-12 08:43 UTC
